# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nvgm < Formula
  desc ""
  homepage "https://github.com/Golgautier/nutanix_vg_manager"
  version "0.2.1"

  on_macos do
    url "https://github.com/Golgautier/nutanix_vg_manager/releases/download/v0.2.1/nutanix_vg_manager_0.2.1_darwin_all.tar.gz"
    sha256 "f5a27c80f878f45939693d934ebc83c3ee7e970bcbd3de161f350d7aa6efa5f8"

    def install
      bin.install "nvgm"
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Golgautier/nutanix_vg_manager/releases/download/v0.2.1/nutanix_vg_manager_0.2.1_linux_amd64.tar.gz"
        sha256 "6a5f664d84abeb58d6006a02dc56ada4975de4137ac21c4ed572cc74314fb288"

        def install
          bin.install "nvgm"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Golgautier/nutanix_vg_manager/releases/download/v0.2.1/nutanix_vg_manager_0.2.1_linux_arm64.tar.gz"
        sha256 "2da23a14587bc587953b4d5f1cabc435f9599bdf050163a2579c2af3f73adc58"

        def install
          bin.install "nvgm"
        end
      end
    end
  end
end
